version: "3"

services:
  mongo_db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db
  
  flask_api:
    volumes:
      - .:/app
    build: .
    depends_on:
      - mongo_db
    ports:
      - "5000:5000"
    links:
      - mongo_db